### Pytorch Tutorial
#### Tensors Basics
1. A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array.It is a term and set of techniques known in machine learning in the training and operation of deep learning models can be described in terms of tensors.

2. In many cases tensors are used as a "replacement for NumPy to use the power of GPUs".

3. Tensors are a type of data structure used in linear algebra, and like vectors and matrices, you can calculate arithmetic operations with tensors.

4. Tensors were used because to use the power of GPUs

In [1]:
import torch

In [3]:
torch.__version__

'2.7.1+cu126'

In [4]:
import numpy as np

In [6]:
lst=[3,4,5,6]
arr=np.array(lst)

In [7]:
arr

array([3, 4, 5, 6])

In [8]:
arr.dtype

dtype('int64')

### Convert Numpy To Pytorch Tensors

In [18]:
tensors=torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6])

In [ ]:
### Indexing similar to numpy
tensors[2]

tensor(5)

In [20]:
tensors[1:4]

tensor([4, 5, 6])

In [65]:
#### Disadvantage of from_numpy. The array and tensor uses the same memory location
tensors[3]=100

In [66]:
tensors

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [23]:
arr # the change is happening in arr as well, because they usually share the same memory loaction

array([3, 4, 5, 6])

In [24]:
### Prevent this by using torch.tensor
tensor_arr=torch.tensor(arr) # prevents the shared memory of array
tensor_arr

tensor([3, 4, 5, 6])

In [25]:
tensor_arr[3]=120
print(tensor_arr)
print(arr)

tensor([  3,   4,   5, 120])
[3 4 5 6]


In [26]:
##zeros and ones
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [27]:
torch.ones(2,3,dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [28]:
a=torch.tensor(np.arange(0,15).reshape(5,3))

In [29]:
a[:,0:2]

tensor([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13]])

##### Arithmetic Operation

In [30]:
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a + b)

tensor([ 7.,  9., 11.])


In [31]:
torch.add(a,b)

tensor([ 7.,  9., 11.])

In [32]:
c=torch.zeros(3)

In [33]:
torch.add(a,b,out=c)

tensor([ 7.,  9., 11.])

In [34]:
c

tensor([ 7.,  9., 11.])

In [35]:
##### Some more operations
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)

In [36]:
### tensor[7,9,15]
torch.add(a,b).sum()

tensor(27.)

##### Dot Products and Mult Operations

In [37]:
x= torch.tensor([3,4,5], dtype=torch.float)
y = torch.tensor([4,5,6], dtype=torch.float)

In [47]:
x.mul(y)

tensor([12., 20., 30.])

#### 3*4+5*4+6*5

In [48]:
x.dot(y)

tensor(62.)

#### MATRIX Multiplication

1. torch.matmul(x,y)
2. torch.mm(x,y)
3. x@y

In [39]:
x = torch.tensor([[1,4,2],[1,5,5]], dtype=torch.float)
y = torch.tensor([[5,7],[8,6],[9,11]], dtype=torch.float)

In [40]:
torch.matmul(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [41]:
torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [42]:
x@y

tensor([[55., 53.],
        [90., 92.]])